services:
  client:
    container_name: "client"
    build: ./client
    ports: -3000:3000

  server:
    container_name: "server"
    build: ./server
    ports: -5000:5000
    depends_on:
      - redis
      - postgres

  redis:
    container_name: "redis"
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001

  postgres:
    container_name: "postgres"
    image: "postgres"
    ports:
      - 5432:5432
